name: Update Examples Cron

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  update-examples-cron:
    if: github.repository == 'grafana/pyroscope'
    runs-on: ${{ github.repository_owner == 'grafana' && 'ubuntu-x64-small' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: 'false'
      - id: get-github-app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@580590a644e82e79bb2598bdaba0be245a14dda0 # create-github-app-token/v0.2.2
        with:
          github_app: pyroscope-development-app

      - run: |
          make tools/update_examples
          if ! git diff --exit-code;
          then
            make tools/update_examples_pr
          fi
        env:
          GITHUB_TOKEN: ${{ steps.get-github-app-token.outputs.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
